### ISSUE TITLE
Should we include a tslint and .editorconfig file in the create-app scaffolding

### ISSUE THREAD

**Issue by tomdye** [dojo/cli-create-app#2]
Currently the WIP implementation of `cli-create-app` scaffolds a `tslint.json` and a `.editorconfig` file. Do we think these should be part of the scaffolding of a new Dojo 2 app?

**Comment by tomdye** [comment]
I think that we should scaffold them, but perhaps the `tslint.json` file should be empty so as not to force a user down our own coding guidelines yet show them where to put theirs?

**Comment by agubler** [comment]
I certainly agree with @matt-gadd that we shouldn't be scaffolding users with **our** internal `tslint.json` and `.editorconfig` files.

We don't have anything in the CLI (either as part of build or a separate command) that actually runs any linting.... We could add a command for linting and then provide a shell `tslint.json` configuration file maybe just extending the recommended settings.

``` json
{
  "extends": "tslint:recommended",
}
```

**Comment by rishson** [comment]
Good question. I'd say that `create` is not the place to be opinionated and therefore I'd not include those 2 files. To my mind, `create` should scaffold out an app by creating the fewest files needed to edit, run and test an app. We're going to have to document what each file created is, and I think users will get overwhelmed if there are lots of files.

**Comment by kitsonk** [comment]
I would say it would be great to offer some sort of option to allow scaffolding of other meta data like this.  We believe that people should use a linter, it is good practice, and we should make it easy to allow it and even maybe difficult to forget it as well as say "hey this works for us, maybe you can use it too"... Since `create` is opinionated way of structuring a good application, we should exercise opinions.

`.editorconfig` is a slightly different story... I think we should omit it, even though it provides whitespacing, I say it is easily something that we can say "be consistent in whitespacing and enforce it with a linter" where as `.editorconfig` is really environment configuration data of where we shouldn't really be opinionated about.

**Comment by agubler** [comment]
We really want to be config free though, wouldn't a better way be opinionated through an installable command? like `dojo lint`? The user can eject (pending this ability) from the CLI if they want to customise this further?

**Comment by tomdye** [comment]
the `tslint.json` gets used by the user's IDE as well @agubler so it's required at dev time, not at `dojo lint` time.

**Comment by agubler** [comment]
It **can** be used by the IDE, but that is a reasonable point.

**Comment by agubler** [comment]
So for me if we are going to add a `tslint.json` it should just be configured with the tslint recommended rules. So we are opinionated that we think they should use one, but not about specific rules.

**Comment by rishson** [comment]
Related but in a different command, do we fail `build` in `cli` if there are tslint errors?

**Comment by agubler** [comment]
@rishson negative, currently the build does not run any linting.

**Comment by kitsonk** [comment]
I know we are config free by default, but surely we can express additional configuration if necessary (e.g. swap a default `tslint.json` for something else)?  Even if we revisited the `tslint.json` for scaffolding and made it less opinionated around Dojo 2 and only assert "best practices" instead of using our one.

Personal opinion again, I think we should have an strong opinion that linting is part of a good build process, so I feel `build` should perform linting by default.  If we are going to scaffold out tests, we should scaffold out a whole best practice toolchain.

**Comment by rishson** [comment]
There is no harm in suggesting best practise and I think linting is part of that. Running `tslint` with `recommended` settings during `build` and/or `test`, sounds like a positive move. I'm still unsure if we should fail a build or test run though - or just warn the user. Whilst failing a build is a good practise, to a new user, just playing round with an app to get to grips with things, not letting them edit + see changes till their code is perfect, could well have negative learning effects.
Maybe fail a `test` but warn in `build`?

**Comment by agubler** [comment]
@kitsonk as @Tomdye stated, for the `tslint.json` we'd probably want to "add" the config file in this case so that the settings can be used by consumers IDEs.

We could always recommended `sidekickjs` 😄

**Comment by rishson** [comment]
![screen shot 2016-09-22 at 10 43 15 am](https://cloud.githubusercontent.com/assets/468596/18743558/782cb52c-80b1-11e6-8dd2-d594bb51588f.png)

`todoMVC` is in pretty good shape 😄

**Comment by kitsonk** [comment]
I wouldn't say no to `sidekickjs`.

**Comment by tomdye** [comment]
Ill got with `tslint` recomended settings for now then and I'll drop the `.editorconfig` file, thanks all for your input

**Comment by matt-gadd** [comment]
I wonder whether we should bundle the tsling config with a `lint` command? I'm definitely at least leaning towards a `lint` command, as I don't want to couple it in to the `build` or `test` tasks, and would rather run the `lint` command as pre-requisite.

**Comment by agubler** [comment]
Slight offline discussion, we will have a `dojo lint` command that will add the `tslint.json` to the users project and will be part of the recommended default commands.

This will allow us to have "other" linting commands, for example `dojo lint sidekick` etc etc and then the `dojo build` will be able to call out to the users installed linting command optionally as part of its work.

**Comment by tomdye** [comment]
Going to close this issue as it appears to be settled.
